#!/usr/bin/env python

from bevel import BDict

if __name__ == '__main__':
	from sys import argv
	files = argv[1:]
	bdicts = [BDict(fname) for fname in files]
	for bdict in bdicts:
		for item in bdict.list():
			print bdict.name, ':', item[0], ':', item[1]
