#!/usr/bin/env python
"""
Grep through keys and values in a bencoded entity.
"""

from bevel import BEnt, tokenize
from bencode.BTL import BTFailure
import sys
import argparse

SEPARATOR = ':'
KEY_SEPARATOR = '.'

if __name__ == '__main__':
	parser = argparse.ArgumentParser(description = __doc__)
	parser.add_argument('--no-filename', '-H', action='store_true', default=False, help='suppress prefixing filenames to results')
	parser.add_argument('--separator', '-s', default=SEPARATOR, help='override default separator (defaults to \''+SEPARATOR+'\')')
	parser.add_argument('--key-separator', '-k', default=KEY_SEPARATOR, help='override default key separator (defaults to \''+KEY_SEPARATOR+'\')')
	parser.add_argument('--print0', '-0', action='store_true', help='use null as line separator')
	parser.add_argument('keys', nargs=1, help='a comma-separated list of keys, which may be globs')
	parser.add_argument('files', nargs='+')
	args = parser.parse_args()
	keyvalues = [key for key in tokenize(args.keys[0],',')]
	for fname in args.files:
		try:
			bdict = BEnt(fname, args.key_separator, args.separator)
		except (BTFailure, IOError):
			print >> sys.stderr, 'skipping '+fname+' as an invalid bencoded entity...'
			continue
		prefix = '' if args.no_filename else bdict.name+args.separator
		for item in bdict.lookup(keyvalues):
			sys.stdout.write(prefix+str(item[0])+args.separator+str(item[1])+('\0' if args.print0 else '\n'))
	try:
		sys.stdout.flush()
	except IOError:
		pass
