#!/usr/bin/env python

from bevel import BTDict

if __name__ == '__main__':
	from sys import argv
	keyvalues = [tuple(pair.split('=')) for pair in argv[1].split(',')]
	files = argv[2:]
	bdicts = [BDict(fname) for fname in files]
	for bdict in bdicts:
		bdict.set(keyvalues)
